site_name: Pyestro Documentation
site_description: Python Configuration Management Orchestrator
site_author: Your Name

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Commands: user-guide/commands.md
    - Reclass Integration: user-guide/reclass.md
    - Ansible Integration: user-guide/ansible.md
  - Developer Guide:
    - Architecture: developer-guide/architecture.md
    - API Reference: developer-guide/api.md
    - Contributing: developer-guide/contributing.md
  - Reference:
    - Configuration Schema: reference/config-schema.md
    - CLI Reference: reference/cli.md
    - Migration Guide: reference/migration.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html

plugins:
  - search
  - autorefs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourname/pyestro

